# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0688b45094990b6a4187422bc5b79dcb7002f3430bb5b07d5ab5fcc6e1f965c6e07b0e8cd7a5584148cfda276b51612549f9367270cb2c9adde13bfd91185e13

test:
  secret_key_base: 612ecd9539fa6c7e8d9cec2f417f99872958f4694a70521a66b83d519509854c7ff7ed28bc3502b347813dbd4804227791ecb00f9eb18b943bdb0036abe3b3ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
